# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi_app_hs <- function(treemat, node_indices, internalmat, xmat) {
    .Call(`_HSMOTRBART_phi_app_hs`, treemat, node_indices, internalmat, xmat)
}

